Description: Oliver / Deploy Server infrastructure

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  InstanceAMI: 
    Description: The amazon machine image id
    Type: String
    Default: ami-04902260ca3d33422

  InstanceKeyName: 
    Description: Key name to use for jumper instance
    Type: String
    Default: my_instance_1

Resources:

  RoleForSMAccess:
    Type: AWS::IAM::Role
    Properties:
      Description: Create session manager role
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Roles:
        - !Ref RoleForSMAccess

  ServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: "t3.micro"
      ImageId: !Ref InstanceAMI
      IamInstanceProfile: !Ref InstanceProfile
      KeyName: !Ref InstanceKeyName
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: 
            Fn::ImportValue:
              !Sub "${EnvironmentName}-PUB1-SN"
          GroupSet:
            - Ref: ServerSecGroup
